// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaLrapEHrJKBd8hqtZmNlhOQlsODGdasc',
    appId: '1:517377863058:web:a59ca5c7e223dca9ace54b',
    messagingSenderId: '517377863058',
    projectId: 'flutter-practice-tasks',
    authDomain: 'flutter-practice-tasks.firebaseapp.com',
    storageBucket: 'flutter-practice-tasks.firebasestorage.app',
    measurementId: 'G-EDPN94WMQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA36D0cPbcQcDIFWbJn4eie2hc5uDGRCcw',
    appId: '1:517377863058:android:e2854899d29b7240ace54b',
    messagingSenderId: '517377863058',
    projectId: 'flutter-practice-tasks',
    storageBucket: 'flutter-practice-tasks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKrljHjhE21nx2TkqL9zQ-Vt3hrX_vGg',
    appId: '1:517377863058:ios:d7fe4782affefb25ace54b',
    messagingSenderId: '517377863058',
    projectId: 'flutter-practice-tasks',
    storageBucket: 'flutter-practice-tasks.firebasestorage.app',
    iosBundleId: 'com.example.flutterpractisetasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKrljHjhE21nx2TkqL9zQ-Vt3hrX_vGg',
    appId: '1:517377863058:ios:d7fe4782affefb25ace54b',
    messagingSenderId: '517377863058',
    projectId: 'flutter-practice-tasks',
    storageBucket: 'flutter-practice-tasks.firebasestorage.app',
    iosBundleId: 'com.example.flutterpractisetasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaLrapEHrJKBd8hqtZmNlhOQlsODGdasc',
    appId: '1:517377863058:web:2b61634a8c510c18ace54b',
    messagingSenderId: '517377863058',
    projectId: 'flutter-practice-tasks',
    authDomain: 'flutter-practice-tasks.firebaseapp.com',
    storageBucket: 'flutter-practice-tasks.firebasestorage.app',
    measurementId: 'G-XDYPEMC8MF',
  );
}
